# Generated by Django 5.0.1 on 2024-01-28 22:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=30, size=None)),
                ('quiz_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizinfo')),
            ],
        ),
    ]
