# Generated by Django 4.2.4 on 2025-10-22 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acutest_text',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=91, size=None),
        ),
    ]
