# Generated by Django 5.0.1 on 2024-02-05 18:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_acutest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acutest',
            name='Answers',
        ),
        migrations.AlterField(
            model_name='quizinfo',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ValuTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=30, size=None)),
                ('quiz_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizinfo')),
            ],
        ),
        migrations.AddField(
            model_name='acutest',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], max_length=30, size=None),
            preserve_default=False,
        ),
    ]
