# Generated by Django 4.2.4 on 2025-10-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_acutest_text_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acutest_pic',
            name='quiz_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiztime'),
        ),
    ]
