# Generated by Django 4.2.4 on 2025-10-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_acutest_pic_quiz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acutest_text',
            name='quiz_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiztime'),
        ),
        migrations.AlterField(
            model_name='valutest',
            name='quiz_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quiztime'),
        ),
    ]
