# Generated by Django 5.0.1 on 2024-02-07 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_acutest_answers_alter_quizinfo_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acutest',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=43, size=None),
        ),
    ]
