# Generated by Django 4.2.4 on 2025-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_acutest_text_quiz_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acutest_pic',
            name='no_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_pic',
            name='no_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_pic',
            name='num_of_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_pic',
            name='num_of_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_pic',
            name='yes_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_pic',
            name='yes_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_text',
            name='no_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_text',
            name='no_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_text',
            name='num_of_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_text',
            name='num_of_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_text',
            name='yes_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acutest_text',
            name='yes_yes',
            field=models.IntegerField(default=0),
        ),
    ]
