# Generated by Django 4.2.4 on 2025-12-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_acutest_pic_no_no_acutest_pic_no_yes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acutest_pic',
            name='no_no',
        ),
        migrations.RemoveField(
            model_name='acutest_pic',
            name='no_yes',
        ),
        migrations.RemoveField(
            model_name='acutest_pic',
            name='num_of_no',
        ),
        migrations.RemoveField(
            model_name='acutest_pic',
            name='num_of_yes',
        ),
        migrations.RemoveField(
            model_name='acutest_pic',
            name='yes_no',
        ),
        migrations.RemoveField(
            model_name='acutest_pic',
            name='yes_yes',
        ),
    ]
