# Generated by Django 5.0.1 on 2024-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutest',
            name='esteghlal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valutest',
            name='hemayat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valutest',
            name='pishraft',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valutest',
            name='ravabet',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valutest',
            name='sharayet_kari',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valutest',
            name='tofigh',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
