# Generated by Django 4.2.4 on 2026-01-07 10:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def migrate_user_to_account(apps, schema_editor):
    """Copy user_id - 1 to account_id for each model"""
    Acutest_pic = apps.get_model("quiz", "Acutest_pic")
    Acutest_text = apps.get_model("quiz", "Acutest_text")
    Valutest = apps.get_model("quiz", "Valutest")

    for obj in Acutest_pic.objects.all():
        if obj.user_id is not None:
            obj.account_id = obj.user_id - 1
        else:
            obj.account_id = 4  # fallback default
        obj.save()

    for obj in Acutest_text.objects.all():
        if obj.user_id is not None:
            obj.account_id = obj.user_id - 1
        else:
            obj.account_id = 4  # fallback default
        obj.save()

    for obj in Valutest.objects.all():
        if obj.user_id is not None:
            obj.account_id = obj.user_id - 1
        else:
            obj.account_id = 4  # fallback default
        obj.save()


def reverse_migrate(apps, schema_editor):
    """Reverse: copy account_id + 1 back to user_id"""
    Acutest_pic = apps.get_model("quiz", "Acutest_pic")
    Acutest_text = apps.get_model("quiz", "Acutest_text")
    Valutest = apps.get_model("quiz", "Valutest")

    for obj in Acutest_pic.objects.all():
        if obj.account_id is not None:
            obj.user_id = obj.account_id + 1
        obj.save()

    for obj in Acutest_text.objects.all():
        if obj.account_id is not None:
            obj.user_id = obj.account_id + 1
        obj.save()

    for obj in Valutest.objects.all():
        if obj.account_id is not None:
            obj.user_id = obj.account_id + 1
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0009_rename_acutest_permition_account_acutest_permission_and_more",
        ),
        ("quiz", "0006_remove_acutest_pic_no_no_remove_acutest_pic_no_yes_and_more"),
    ]

    operations = [
        # 1. AlterModelOptions (these can stay at the top)
        migrations.AlterModelOptions(
            name="acutest_pic",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Acuity Test (Picture)",
                "verbose_name_plural": "Acuity Tests (Picture)",
            },
        ),
        migrations.AlterModelOptions(
            name="acutest_text",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Acuity Test (Text)",
                "verbose_name_plural": "Acuity Tests (Text)",
            },
        ),
        migrations.AlterModelOptions(
            name="quiztime",
            options={"verbose_name": "Quiz Time", "verbose_name_plural": "Quiz Times"},
        ),
        migrations.AlterModelOptions(
            name="valutest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Values Test",
                "verbose_name_plural": "Values Tests",
            },
        ),
        # 2. ADD the account field first (nullable temporarily)
        migrations.AddField(
            model_name="acutest_pic",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acutest_pics",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="acutest_text",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acutest_texts",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="valutest",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valutests",
                to="account.account",
            ),
        ),
        # 3. RUN data migration (user still exists at this point!)
        migrations.RunPython(migrate_user_to_account, reverse_migrate),
        # 4. NOW remove the user field (data has been copied)
        migrations.RemoveField(
            model_name="acutest_pic",
            name="user",
        ),
        migrations.RemoveField(
            model_name="acutest_text",
            name="user",
        ),
        migrations.RemoveField(
            model_name="valutest",
            name="user",
        ),
        # 5. Make account field non-nullable
        migrations.AlterField(
            model_name="acutest_pic",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acutest_pics",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="acutest_text",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acutest_texts",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="valutest",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valutests",
                to="account.account",
            ),
        ),
        # 6. Add created_at fields
        migrations.AddField(
            model_name="acutest_pic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2026-01-07T08:34:40.681Z"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acutest_text",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2026-01-07T08:34:40.681Z"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="valutest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2026-01-07T08:34:40.681Z"
            ),
            preserve_default=False,
        ),
        # 7. AlterFields for other changes
        migrations.AlterField(
            model_name="acutest_pic",
            name="answers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=43
            ),
        ),
        migrations.AlterField(
            model_name="acutest_pic",
            name="quiz_time",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acutest_pic",
                to="quiz.quiztime",
            ),
        ),
        migrations.AlterField(
            model_name="acutest_text",
            name="answers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=91
            ),
        ),
        migrations.AlterField(
            model_name="acutest_text",
            name="quiz_time",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acutest_text",
                to="quiz.quiztime",
            ),
        ),
        migrations.AlterField(
            model_name="valutest",
            name="answers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=30
            ),
        ),
        migrations.AlterField(
            model_name="valutest",
            name="quiz_time",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="valutest",
                to="quiz.quiztime",
            ),
        ),
    ]
