# Generated by Django 4.2.4 on 2026-05-03 19:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_email'),
        ('quiz', '0007_alter_acutest_pic_options_alter_acutest_text_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HexacoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hexacotest', to='account.account')),
                ('quiz_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hexacotest', to='quiz.quiztime')),
            ],
            options={
                'verbose_name': 'Hexaco Test',
                'verbose_name_plural': 'Hexaco Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BelbinTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=56)),
                ('cf', models.IntegerField(default=0)),
                ('tw', models.IntegerField(default=0)),
                ('imp', models.IntegerField(default=0)),
                ('me', models.IntegerField(default=0)),
                ('ri', models.IntegerField(default=0)),
                ('pl', models.IntegerField(default=0)),
                ('co', models.IntegerField(default=0)),
                ('sh', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belbintest', to='account.account')),
                ('quiz_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belbintest', to='quiz.quiztime')),
            ],
            options={
                'verbose_name': 'Belbin Test',
                'verbose_name_plural': 'Belbin Tests',
                'ordering': ['-created_at'],
            },
        ),
    ]
