# Generated by Django 4.2.4 on 2026-05-15 00:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_thinktest_permission'),
        ('quiz', '0009_hexacotest_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThinkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=list, size=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thinktest', to='account.account')),
                ('quiz_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thinktest', to='quiz.quiztime')),
            ],
            options={
                'verbose_name': 'Think Test',
                'verbose_name_plural': 'Think Tests',
                'ordering': ['-created_at'],
            },
        ),
    ]
