ACU_TEST_PIC_TIMELIMIT_SECONDS = 60 * 5 + 10
ACU_TEST_TEXT_TIMELIMIT_SECONDS = 60 * 6 + 10
VALU_TEST_TIMELIMIT_SECONDS = 60 * 180

ACU_TEST_PIC_QUESTION_COUNT = 42
ACU_TEST_TEXT_QUESTION_COUNT = 90
VALU_TEST_QUESTION_COUNT = 20
