ACU_TEST_PIC_TIMELIMIT_SECONDS = 60 * 10 + 10
ACU_TEST_TEXT_TIMELIMIT_SECONDS = 60 * 10 + 10
VALU_TEST_TIMELIMIT_SECONDS = 60 * 180

ACU_TEST_PIC_QUESTION_COUNT = 50
ACU_TEST_TEXT_QUESTION_COUNT = 50
VALU_TEST_QUESTION_COUNT = 70
