export interface Choice {
    text: string;
    score: number;
}

export interface Question {
    id: number;
    text: string;
    choices: Choice[];
}

export const standardChoices: Choice[] = [
    { text: 'کاملاً مخالف', score: 1 },
    { text: 'مخالف', score: 2 },
    { text: 'نه موافق نه مخالف', score: 3 },
    { text: 'موافق', score: 4 },
    { text: 'کاملاً موافق', score: 5 }
];

export const hexacoQuestions: Question[] = [
    { id: 1, text: 'بازدید از نمایشگاه هنری برایم تا حدودی کسل کننده است.', choices: standardChoices },
    { id: 2, text: 'غالبا دفتر کار یا خانه ام را تمیز می کنم.', choices: standardChoices },
    { id: 3, text: 'بندرت کينه کسي را به دل مي گيرم، حتي اگر بدجوري با من رفتار کرده باشند. ', choices: standardChoices },
    { id: 4, text: 'در كل تا حد معقولی از خودم رضايت دارم.', choices: standardChoices },
    { id: 5, text: 'اگر مجبور شوم در شرايط بد آب و هوايي مسافرت کنم، می ترسم. ', choices: standardChoices },
    { id: 6, text: 'اگر از کسی که دوستش ندارم چيزي بخواهم، براي به دست آوردن آن خيلي دوستانه با او رفتار می کنم. ', choices: standardChoices },
    { id: 7, text: 'علاقه دارم مطالبي را در مورد تاريخ و سياست ساير كشورها بياموزم.', choices: standardChoices },
    { id: 8, text: 'اغلب هنگام کار، اهداف جاه طلبانه اي را براي خودم تعيين مي کنم. ', choices: standardChoices },
    { id: 9, text: ' مردم گاهي به من مي گويند که خيلي از ديگران انتقاد مي کنم. ', choices: standardChoices },
    { id: 10, text: 'در جلسات گروهي به ندرت عقايد و نظراتم را بيان مي کنم. ', choices: standardChoices },
    { id: 11, text: 'گاهي نگراني ای که درباره موضوعات جزئي در من ایجاد می شود، در اختیار خودم نیست.', choices: standardChoices },
    { id: 12, text: 'اگر بدانم که هرگز گرفتار نمی شوم، قبول می کنم که يک ميليارد تومان سرقت کنم. ', choices: standardChoices },
    { id: 13, text: 'شغلي را دوست دارم كه يكنواخت باشد تا اينكه نياز به خلاقيت داشته باشد. ', choices: standardChoices },
    { id: 14, text: 'غالبا كارم را بارها و بارها بررسى مى كنم تا اگر اشتباهاتى وجود دارد آنها را پيدا و رفع كنم.', choices: standardChoices },
    { id: 15, text: 'مردم گاهي به من مي گويند که خيلي کله شق و لجباز هستم.', choices: standardChoices },
    { id: 16, text: 'از گپ زدن با دیگران اجتناب می کنم.', choices: standardChoices },
    { id: 17, text: 'هنگامي که از تجربه دردناکي رنج مي برم، نياز دارم که کسي مرا دلداري بدهد. ', choices: standardChoices },
    { id: 18, text: 'داشتن پول خيلي زياد برايم اهميت زيادي ندارد. ', choices: standardChoices },
    { id: 19, text: 'فکر می کنم توجه کردن به افکار سیاسی و اجتماعی افراطی نوعی اتلاف وقت است.', choices: standardChoices },
    { id: 20, text: 'به جاي اين كه دقيق فكر كنم، بر اساس احساسات لحظه اي تصميم مي گيرم.', choices: standardChoices },
    { id: 21, text: 'ديگران فکر مي کنند که من آدم تندمزاجي هستم.', choices: standardChoices },
    { id: 22, text: 'تقريباً هميشه پرانرژي هستم. ', choices: standardChoices },
    { id: 23, text: 'وقتي ديگران را درحال گريه کردن مي بينم، دلم مي خواهد گريه کنم. ', choices: standardChoices },
    { id: 24, text: 'من يک فرد معمولي هستم و از ديگران بهتر نيستم. ', choices: standardChoices },
    { id: 25, text: 'وقتم را صرف خواندن کتاب شعر نمي کنم. ', choices: standardChoices },
    { id: 26, text: 'به منظور اجتناب از بي نظمي و عجله در لحظه آخر، از قبل کارهايم را برنامه ريزي و سازماندهي مي کنم. ', choices: standardChoices },
    { id: 27, text: 'نگرش من نسبت به افرادي که با من بدرفتاري کرده اند، «بخشش و گذشت» است. ', choices: standardChoices },
    { id: 28, text: 'فكر مي كنم كه اكثر مردم برخي از جنبه هاي شخصيت مرا دوست دارند.', choices: standardChoices },
    { id: 29, text: 'از انجام دادن مشاغلی که شامل کارهای خطرناک اند، واهمه ای ندارم.', choices: standardChoices },
    { id: 30, text: 'حاضر نيستم براي ترفيع يا ارتقاء در شغل خود چاپلوسي کنم، حتي اگر آن چاپلوسی باعث موفقيت من شود. ', choices: standardChoices },
    { id: 31, text: 'از نگاه کردن به نقشه ی جاهاي مختلف لذت مي برم. ', choices: standardChoices },
    { id: 32, text: 'هنگام تلاش برای رسيدن به هدف، اغلب به خودم به شدت فشار مي آورم. ', choices: standardChoices },
    { id: 33, text: 'معمولا بدون این که از نقایص وعیبهای دیگران شکایتی بکنم، آنها را می پذیرم. ', choices: standardChoices },
    { id: 34, text: 'در موقعيت هاي اجتماعي، معمولاً اولين کسي هستم که برای انجام دادن کاری پیش قدم می شود.', choices: standardChoices },
    { id: 35, text: 'خيلي کمتر از اكثر مردم نگران مي شوم.', choices: standardChoices },
    { id: 36, text: 'اگر از لحاظ مالي در مضيقه باشم، وسوسه مي شوم که اموال دزدي را خريداري کنم. ', choices: standardChoices },
    { id: 37, text: 'از خلق کارهاي هنري از قبيل يك داستان، يك آهنگ و يا يك نقاشي لذت مي برم. ', choices: standardChoices },
    { id: 38, text: 'هنگام انجام دادن کاری، به جزئيات کم اهميت آن توجه چندانی نمي کنم. ', choices: standardChoices },
    { id: 39, text: 'وقتي ديگران با نظر من مخالف هستند، معمولاً انعطاف پذیری کافی را در عقايدم نشان می دهم. ', choices: standardChoices },
    { id: 40, text: 'دوست دارم آدم هاي زيادي در اطراف من باشند تا با آنها صحبت کنم. ', choices: standardChoices },
    { id: 41, text: 'بدون نياز به حمايت عاطفي ديگران مي توانم از موقعيت هاي دشوار سربلند بیرون بیایم. ', choices: standardChoices },
    { id: 42, text: 'دوست دارم در محله هاي گران و سطح بالا زندگي کنم. ', choices: standardChoices },
    { id: 43, text: 'از آدم هايي که ديدگاه هاي غير سنتي دارند، خوشم مي آيد. ', choices: standardChoices },
    { id: 44, text: 'چون قبل از عمل، به مقدار کافی فکر نمي کنم، اشتباهات زيادي را مرتکب مي شوم.', choices: standardChoices },
    { id: 45, text: 'حتي اگرکسی با من خيلي بدرفتاری کند، باز هم به ندرت احساس خشم مي كنم. ', choices: standardChoices },
    { id: 46, text: 'در اکثر روزها احساس شادي و خوش بيني مي كنم. ', choices: standardChoices },
    { id: 47, text: 'وقتي که فرد آشنايي را ناراحت مي بينم، تقريباً مي توانم درد آن شخص را احساس کنم. ', choices: standardChoices },
    { id: 48, text: 'نمي خواهم مردم با من طوري رفتار کنند که گویی از آنها برتر هستم. ', choices: standardChoices },
    { id: 49, text: 'اگر فرصت داشته باشم دوست دارم در کنسرت موسيقي کلاسيک حضور پيدا كنم.', choices: standardChoices },
    { id: 50, text: 'غالباً شلوغی و بی نظمی اتاق يا ميزم، یکی از موضوعات شوخی های دوستان من است. ', choices: standardChoices },
    { id: 51, text: 'کافی است کسي يک بار مرا فريب داده باشد، در این صورت هميشه نسبت به او بدبين می شوم. ', choices: standardChoices },
    { id: 52, text: 'احساس مي كنم كه فرد مردم پسندي نيستم.', choices: standardChoices },
    { id: 53, text: 'زماني که خطر جسمي در پيش باشد، خيلي مي ترسم. ', choices: standardChoices },
    { id: 54, text: 'اگر از کسی چیزی بخواهم به بی مزه ترین لطیفه های او نیز می خندم.', choices: standardChoices },
    { id: 55, text: 'خواندن کتاب هاي مربوط به تاريخ علم و فن آوري برایم کسل کننده است. ', choices: standardChoices },
    { id: 56, text: 'غالبا وقتی هدفی را برای خودم تعیین می کنم، پیش از رسیدن به آن هدف، رهایش می کنم.', choices: standardChoices },
    { id: 57, text: 'در قضاوت راجع به ديگران سخت نمي گيرم.', choices: standardChoices },
    { id: 58, text: 'وقتي در گروهی هستم، غالباً اولين کسي هستم که به نمايندگي از طرف گروه صحبت مي کنم. ', choices: standardChoices },
    { id: 59, text: 'به ندرت، به خاطر فشار رواني يا اضطراب به بدخوابي دچار مي شوم. ', choices: standardChoices },
    { id: 60, text: 'هر قدر هم که مبلغ رشوه زياد باشد، حاضر به پذيرفتن آن نيستم. ', choices: standardChoices },
    { id: 61, text: 'ديگران اغلب به من گفته اند که از قوه ی تخيل خوبي برخوردارم.', choices: standardChoices },
    { id: 62, text: 'هميشه سعي مي کنم در کارم دقيق باشم، حتي اگر وقت را از دست بدهم. ', choices: standardChoices },
    { id: 63, text: 'وقتی دیگران به من می گویند که راجع به مساله ای در اشتباهم، اولین واکنش من جروبحث با آنها است.', choices: standardChoices },
    { id: 64, text: ' کارکردن در موقعيت تعامل اجتماعي فعال را به تنها کار کردن ترجيح مي دهم. ', choices: standardChoices },
    { id: 65, text: 'هر گاه که راجع به چيزي نگران مي شوم، دوست دارم آن را با کسي در ميان بگذارم. ', choices: standardChoices },
    { id: 66, text: 'دوست دارم ديگران مرا در حال رانندگي با ماشين خيلي گران قيمت ببينند. ', choices: standardChoices },
    { id: 67, text: 'تا حدودي خودم را فردي عجیب و غیرعادی مي دانم. ', choices: standardChoices },
    { id: 68, text: 'اجازه نمي دهم تكانه ها و انگيزه هاي ناگهاني رفتارم را تعیین کنند.  ', choices: standardChoices },
    { id: 69, text: 'اکثر افراد زود تر از من عصباني مي شوند. ', choices: standardChoices },
    { id: 70, text: 'مردم اغلب به من مي گويند که بايد سعي کنم سرحال و بشاش باشم. ', choices: standardChoices },
    { id: 71, text: 'زماني که يك دوست صميمي براي مدت طولاني از من دور مي شود، خیلی احساساتي مي شوم.  ', choices: standardChoices },
    { id: 72, text: 'فکر مي کنم بيشتر از يك فرد معمولي لایق احترام هستم. ', choices: standardChoices },
    { id: 73, text: 'گاهي دوست دارم بادي را که از لابلاي درختان مي وزد تماشا کنم. ', choices: standardChoices },
    { id: 74, text: 'گاهي هنگام کار، به علت بي نظمي خودم، با مشکل مواجه مي شوم.', choices: standardChoices },
    { id: 75, text: 'اگر فردي به من بدي كرده باشد، بخشش کامل او برايم دشوار است. ', choices: standardChoices },
    { id: 76, text: 'گاهی اوقات احساس مي كنم كه شخص بي ارزشي هستم.', choices: standardChoices },
    { id: 77, text: 'حتي در موقعيت هاي اضطراري نیز دست و پای خود را گم نمی کنم. ', choices: standardChoices },
    { id: 78, text: ' براي اينكه شخصي لطفي در حق من بكند، تظاهر به دوست داشتن او نمي كنم.  ', choices: standardChoices },
    { id: 79, text: 'هرگز از ورق زدن دايره المعارف لذت نبرده ام. ', choices: standardChoices },
    { id: 80, text: 'در هر امری فقط حداقل کار لازم را انجام می دهم و نه بیشتر.', choices: standardChoices },
    { id: 81, text: 'اگر کسی مرتکب اشتباهات زيادي شود، به ندرت درمورد او اظهار نظر منفي مي كنم. ', choices: standardChoices },
    { id: 82, text: 'معمولا هنگام صحبت در مقابل گروهی از مردم تا حدودی عصبی و دستپاچه می شوم.', choices: standardChoices },
    { id: 83, text: 'هنگامي که منتظر اعلام نتيجه درمورد تصميم مهمي هستم، خيلي مضطرب مي شوم.', choices: standardChoices },
    { id: 84, text: 'اگر مطمئن بودم كه گرفتار نمی شوم، وسوسه می شدم که از اسكناس تقلبي استفاده کنم.', choices: standardChoices },
    { id: 85, text: 'خودم را جزو دسته ی آدم هاي خلاق يا هنرمند نمي دانم. ', choices: standardChoices },
    { id: 86, text: ' ديگران غالباً می گویند که من کمال گرا هستم.  ', choices: standardChoices },
    { id: 87, text: 'وقتي واقعاً فکر مي کنم که حق با من است، مصالحه و توافق با ديگران برايم دشوار است.', choices: standardChoices },
    { id: 88, text: 'اولين کاري که درموقعيت جديد انجام مي دهم، دوست يابي است. ', choices: standardChoices },
    { id: 89, text: ' به ندرت راجع به مشکلاتم با ديگران مشورت مي کنم. ', choices: standardChoices },
    { id: 90, text: 'اگر کالاهاي لوکس گران قيمت داشته باشم، لذت بسیار مي برم.', choices: standardChoices },
    { id: 91, text: 'بحث هاي فلسفي برایم خسته كننده اند.', choices: standardChoices },
    { id: 92, text: ' به جاي پيروي از يک برنامه، ترجيح مي دهم آنچه را  که به ذهنم مي آيد انجام دهم. ', choices: standardChoices },
    { id: 93, text: 'وقتي ديگران در حق من توهين و بي احترامي مي کنند، کنترل عصبانيت برايم دشوار است. ', choices: standardChoices },
    { id: 94, text: 'اکثر افراد سرزنده تر و فعال تر از من هستند.', choices: standardChoices },
    { id: 95, text: 'حتی در موقعیت هایی که بیشتر افراد خیلی احساساتی می شوند، من احساساتی نمی شوم. ', choices: standardChoices },
    { id: 96, text: 'مي خواهم مردم بدانند که شخص بلندپايه و مهمي هستم. ', choices: standardChoices },
    { id: 97, text: 'نسبت به کسانی که به اندازه من خوشبخت نیستند احساس همدردی می کنم.', choices: standardChoices },
    { id: 98, text: 'سعي مي کنم نسبت به نيازمندان سخاوتمندانه رفتار کنم. ', choices: standardChoices },
    { id: 99, text: 'از صدمه زدن به فردی که از او خوشم نمى آيد، احساس ناراحتی نمی کنم. ', choices: standardChoices },
    { id: 100, text: 'دیگران مرا فردی سنگدل وبی احساس می دانند.', choices: standardChoices },
];

