// src/lib/text-quiz-questions.ts

// This array contains all the text-comparison questions for the quiz.
export const textQuizQuestions = [
    // From image_f2293d.png
    { text1: 'Mei Jean Wholesaler', text2: 'Mei Jeen Wholesaler' },
    { text1: 'Teeterboard', text2: 'Teetebooard' },
    { text1: 'Atlas Flagg, Inc.', text2: 'Atlas Flag, Inc.' },
    { text1: 'C.G. Munguia', text2: 'C.G. Munguia' },
    { text1: 'Q & Q Quaint Bazaar', text2: 'Q & Q Quaint Bazar' },
    { text1: 'Bradley Gillberston', text2: 'Bradley Gillbertsen' },
    { text1: 'Hanglas Bakery', text2: 'Hanglas Bakery' },
    { text1: 'Franklin Rd.', text2: 'Franklin Rd.' },
    { text1: 'D.O. Etumu & Sons', text2: 'D.O. Etumu & Sons' },
    { text1: 'Ben Spark', text2: 'Ben Sprak' },
    { text1: 'I.K. Season Corp.', text2: 'I.K. Season Corp.' },
    { text1: "Cole's Heat Systems", text2: "Cole's Heat Systens" },
    { text1: 'Ridgewood Writers', text2: 'Ridgewood Writers' },
    { text1: 'Progressive Svc.', text2: 'Progressive Svc.' },
    { text1: 'Cai Cheung Wax Co.', text2: 'Cai Cheung Wax Co.' },
    { text1: 'Wraner Olukayode', text2: 'Warner Olukayode' },
    { text1: 'Capital Press Center', text2: 'Capitol Press Center' },
    { text1: 'Chesmu Cross C.', text2: 'Chesmu Cross C.' },
    { text1: 'Edwin J. Rotzoll', text2: 'Edwin J. Rotzoll' },
    { text1: 'Harkenville, Jerome', text2: 'Harkenville, Jerome' },
    { text1: 'Dresser Ctge.', text2: 'Dresser Ctge.' },
    { text1: 'Juana N. Parks', text2: 'Juana N. Park' },
    { text1: 'Pobgee Dr.', text2: 'Pogbee Dr.' },
    { text1: 'Anastasia Cowan', text2: 'Anastasia Cowan' },
    { text1: 'Jonina Jannini', text2: 'Jonina Jannini' },
    { text1: 'Velocity Rwys.', text2: 'Velocity Rwys.' },
    { text1: 'Corona Stefan', text2: 'Corona Stefan' },
    { text1: "Co-op Plumbers Ass'n", text2: "Co-op Plumber Ass'n" },
    { text1: 'Big Sky Balloons Co.', text2: 'Big Sky Baloons Co.' },
    { text1: 'Henderson St. Ctr.', text2: 'Hendersen St. Ctr.' },
    { text1: 'Paramore & Co.', text2: 'Paramore & Co.' },
    { text1: 'Bimler', text2: 'Binler' },
    { text1: 'E-Z Neon', text2: 'E-Z Neon' },
    { text1: 'Blackstone', text2: 'Blackstone' },
    { text1: 'Chris Brasch', text2: 'Chris Grasch' },
    { text1: 'A & V Mech.', text2: 'A & V Mech.' },
    { text1: 'Bustamante & Co.', text2: 'Bustamante & Co.' },
    { text1: 'Endospace', text2: 'Endospace' },
    { text1: 'Fran Barber', text2: 'Fran Barber' },
    { text1: 'T.S. Mankus', text2: 'T.S. Mankos' },
    { text1: 'Broadway Dance Co.', text2: 'Broadway Dance Co.' },
    { text1: 'Marine Salvage', text2: 'Marine Salvage' },
    { text1: 'R.V. Knoll', text2: 'R.V. Knoell' },
    { text1: 'Cue Comic', text2: 'Cue Comic' },
    { text1: 'T.A. Bowles', text2: 'T.A. Bowls' },
    { text1: 'Abbey Dwayne', text2: 'Abbey Dwaayne' },
    { text1: 'Sunbeam Lamps', text2: 'Sunbeam Lamps' },
    { text1: 'Waylan R. Massell', text2: 'Waybin R. Massell' },
    { text1: 'Rolon Rodes', text2: 'Rolon Rodes' },
    { text1: 'Genro Dawson Ed.', text2: 'Jenro Dawson Ed.' },
    { text1: 'Anawuye Inc.', text2: 'Anawuuye Inc.' },
    { text1: 'Sungold Stencils', text2: 'Sungold Stencils' },
    { text1: 'Western Steel Wagon', text2: 'Western Steel Wagon' },
    { text1: 'Culp Div.', text2: 'Culp Dir.' },
    { text1: "Carlos' Catering", text2: "Carlos' Catering" },
    { text1: 'J & H Denims', text2: 'J & H Denim' },
    { text1: 'Rashid P.T.', text2: 'Rashed P.T.' },
    { text1: 'J.B. Midori', text2: 'J.B. Midori' },
    { text1: 'Commerce Dr.', text2: 'Commerce Dr.' },
    { text1: 'Ida Muni', text2: 'Ida Muni' },
    { text1: 'Joe T. Bara', text2: 'Jo T. Bara' },
    { text1: 'Allen Div.', text2: 'Allens Div.' },
    { text1: 'Champlain Ave.', text2: 'Champain Ave.' },
    { text1: 'Berlin-Soonam-Fiske', text2: 'Berlin-Soonam-Fiske' },
    { text1: 'I.M. Bonregime', text2: 'I.M. Bonregme' },
    { text1: 'Fairway Golf Course', text2: 'Fareway Golf Course' },
    { text1: 'C.F. Tool & Die', text2: 'C.F. Tool & Die' },
    { text1: 'Donna Brendan', text2: 'Donna Brendon' },
    { text1: 'Village Pizza Place', text2: 'Village Pizza Place' },
    { text1: 'Ardis Deckert', text2: 'Ardis Deckeart' },
    { text1: 'W. Ulfilas', text2: 'W. Ulfilas' },
    { text1: 'Arcway Machine', text2: 'Arcway Machine' },
    { text1: "Gindel's Gages", text2: "Gundel's Gages" },
    { text1: 'Conte Verde Academy', text2: 'Conte Verde Academy' },
    { text1: 'Jina M. Holland Esq.', text2: 'Jina M. Holland Esq.' },
    { text1: 'Neper & Brown Co., Inc.', text2: 'Neper & Brown Co., Inc.' },
    { text1: 'Eve Moemu', text2: 'Eve Moemu' },
    { text1: "Bo Serna's Supply", text2: "Bo Sirna's Supply" },
    { text1: 'Arimoto & Cook, Inc.', text2: 'Arinoto & Cook, Inc.' },
    { text1: 'B.K. Baiamonte Sr.', text2: 'B.K. Bajamonte Sr.' },
    { text1: 'Bryn Mawr Food Mart', text2: 'Bryn Mawyr Food Mart' },
    { text1: 'Lake Shore Day Care', text2: 'Lake Shore Bay Care' },
    { text1: 'Sunland Cement Co.', text2: 'Sunlund Cement Co.' },
    { text1: 'Builders Exchange', text2: 'Builders Exchange' },
    { text1: 'T.R. Humphrey Stores', text2: 'T.R. Humphry Stores' },
    { text1: 'College Cycle Center', text2: 'College Cycle Centre' },
    { text1: 'Kin Flagg', text2: 'Kin Flagg' },
    { text1: 'Phoenix Foundry', text2: 'Phoenix Foundry' },
    { text1: 'Mika Langings', text2: 'Miki Langings' },
    { text1: 'Breeze V.N. & Co.', text2: 'Breeze V.N. & Co.' }
];
