# Generated by Django 5.0.1 on 2024-01-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acuTest_permition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.TextField(choices=[(None, '(Unknown)'), ('MALE ', 'MALE'), ('FEMALE ', 'FEMALE')], default='(Unknown)'),
        ),
        migrations.AddField(
            model_name='account',
            name='valTest_permition',
            field=models.BooleanField(default=False),
        ),
    ]
