# Generated by Django 4.2.4 on 2025-10-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_age_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
