# Generated by Django 4.2.4 on 2025-11-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='degree',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('masters', 'Masters'), ('doctorate', 'Doctorate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
