# Generated by Django 4.2.4 on 2025-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_degree_account_email_account_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='degree',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('student', 'Student'), ('bachelor', 'Bachelor'), ('masters', 'Masters'), ('doctorate', 'Doctorate')], max_length=20, null=True),
        ),
    ]
