# Generated by Django 4.2.4 on 2026-01-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0008_alter_account_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="acuTest_permition",
            new_name="acutest_permission",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="valTest_permition",
            new_name="valutest_permission",
        ),
        migrations.AlterField(
            model_name="account",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="account.organization",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
