# Generated by Django 4.2.4 on 2026-01-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_acutest_permition_account_acutest_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acutest_permission',
            new_name='acuTest_permission',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='valutest_permission',
            new_name='valuTest_permission',
        ),
    ]
