# Generated by Django 4.2.4 on 2026-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_acutest_permission_account_acutest_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='belbinTest_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='hexacoTest_permission',
            field=models.BooleanField(default=False),
        ),
    ]
