# Generated by Django 4.2.4 on 2026-05-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='thinkTest_permission',
            field=models.BooleanField(default=False),
        ),
    ]
